apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: "2022-01-16T19:59:23Z"
  labels:
    app: myapp2
    app.kubernetes.io/component: myapp2
    app.kubernetes.io/instance: myapp2
  name: myapp2
  namespace: cicd
  resourceVersion: "60076"
  uid: 88318d64-1da9-42b3-b00d-c3651e73985e
spec:
  host: myapp2-cicd.crc-dzk9v-master-0.crc.dixq8zxscyo1.instruqt.io
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: myapp2
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2022-01-16T19:59:23Z"
      status: "True"
      type: Admitted
    host: myapp2-cicd.crc-dzk9v-master-0.crc.dixq8zxscyo1.instruqt.io
    routerCanonicalHostname: router-default.crc-dzk9v-master-0.crc.dixq8zxscyo1.instruqt.io
    routerName: default
    wildcardPolicy: None