apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2022-01-16T18:47:48Z"
  generation: 2
  labels:
    app: express-hello-world
    app.kubernetes.io/component: express-hello-world
    app.kubernetes.io/instance: express-hello-world
    app.kubernetes.io/name: express-hello-world
    app.kubernetes.io/part-of: express-hello-world-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-namespace: cicd
  name: express-hello-world
  namespace: cicd
  resourceVersion: "38912"
  uid: 927137ce-6e7b-4270-bb38-c63ec80fa6ae
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: express-hello-world
    deploymentconfig: express-hello-world
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: express-hello-world
        deploymentconfig: express-hello-world
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cicd/express-hello-world@sha256:3cd9ab19b51ce1fdebae8a21240e58a37d19fde42a3be0b68467022338500f5f
        imagePullPolicy: IfNotPresent
        name: express-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - express-hello-world
      from:
        kind: ImageStreamTag
        name: express-hello-world:latest
        namespace: cicd
      lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/cicd/express-hello-world@sha256:3cd9ab19b51ce1fdebae8a21240e58a37d19fde42a3be0b68467022338500f5f
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-16T18:47:59Z"
    lastUpdateTime: "2022-01-16T18:47:59Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: "2022-01-16T18:48:00Z"
    lastUpdateTime: "2022-01-16T18:48:00Z"
    message: replication controller "express-hello-world-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1