apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}-config-map
  namespace: cicd
data:
  example.property.1: hello
  example.property.2: world
  example.property.injectedval: {{ .Values.appname }}
  config1.json: |-
    {
        "val": "key",
        "injval": "{{ .Values.appname }}",
        "x": 5
    }
  example.property.1: hello
  config2.json: |-
{{ tpl (.Files.Get "config.json") . | indent 4 }}
