apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2022-01-16T19:59:23Z"
  labels:
    app: {{ .Values.appname }}
    app.kubernetes.io/component: {{ .Values.appname }}
    app.kubernetes.io/instance: {{ .Values.appname }}
  name: {{ .Values.appname }}
  namespace: cicd
  resourceVersion: "60061"
  uid: dc2a8a01-2e63-498b-bb61-e821d479a911
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentconfig: {{ .Values.appname }}
  sessionAffinity: None
  type: ClusterIP